version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - insider-network

  redis:
    container_name: insider-redis
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD:-batuhan123}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - insider-network

networks:
  insider-network:
    external: true

volumes:
  db-data:
  redis-data: